version: '1'

services:
  BACKEND:
    image: 'backendcloudservice:latest'
    container_name: backend
    build: .
    depends_on:
      - service-db
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://db:3306/netology",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "13111730",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
                "spring.jpa.hibernate.ddl-auto" : "create-drop"
              }'

  service-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=13111730
      - MYSQL_DATABASE=netology
    container_name: db




